if (NOT ROOT_FIND_QUIETLY)
  message(STATUS "Searching for CERN Analysis Framework ROOT")
endif (NOT ROOT_FIND_QUIETLY)

find_program(ROOTCONFIG root-config HINTS $ENV{ROOTSYS})

if (ROOTCONFIG)
	set (ROOT_FOUND TRUE)
	execute_process (COMMAND ${ROOTCONFIG} --incdir OUTPUT_VARIABLE ROOT_INCLUDE_DIR OUTPUT_STRIP_TRAILING_WHITESPACE)
	execute_process (COMMAND ${ROOTCONFIG} --libdir OUTPUT_VARIABLE ROOT_LIB_DIR OUTPUT_STRIP_TRAILING_WHITESPACE)
	execute_process (COMMAND ${ROOTCONFIG} --libs OUTPUT_VARIABLE ROOT_LDFLAGS OUTPUT_STRIP_TRAILING_WHITESPACE)
	execute_process (COMMAND ${ROOTCONFIG} --cflags OUTPUT_VARIABLE ROOT_CPPFLAGS OUTPUT_STRIP_TRAILING_WHITESPACE)

	include_directories(${ROOT_INCLUDE_DIR})
	link_directories(${ROOT_LIB_DIR})

endif (ROOTCONFIG)

if (NOT ROOT_FIND_QUIETLY)
  message(STATUS "Found root-config at ${ROOTCONFIG}")
  message(STATUS "ROOT_INCLUDE_DIR: ${ROOT_INCLUDE_DIR}")
  message(STATUS "ROOT_LIB_DIR: ${ROOT_LIB_DIR}")
  message(STATUS "ROOT_LDFLAGS: ${ROOT_LDFLAGS}")
  message(STATUS "ROOT_CPPFLAGS: ${ROOT_CPPFLAGS}")
endif (NOT ROOT_FIND_QUIETLY)

