if (NOT HDF5++_FIND_QUIETLY)
	message(STATUS "Searching for HDF5 C++ interface")
endif (NOT HDF5++_FIND_QUIETLY)


find_path(HDF5++_INCLUDE_DIRS hdf5++/hdfLLReading.h)
find_library(HDF5++_LIBRARY_DIRS NAMES hdf5++ )
get_filename_component(HDF5++_LIBRARY_DIRS ${HDF5++_LIBRARY_DIRS} PATH)

if (HDF5++_INCLUDE_DIRS AND HDF5++_LIBRARY_DIRS)
	set(HDF5++_FOUND TRUE)
else(HDF5++_INCLUDE_DIRS AND HDF5++_LIBRARY_DIRS)
	set(HDF5++_FOUND FALSE)
endif(HDF5++_INCLUDE_DIRS AND HDF5++_LIBRARY_DIRS)

if (NOT HDF5++_FIND_QUIETLY)
	message(STATUS "HDF5++_INCLUDE_DIRS: ${HDF5++_INCLUDE_DIR}")
	message(STATUS "HDF5++_LIBRARY_DIRS: ${HDF5++_LIBRARY_DIRS}")
	message(STATUS "HDF5++_LDFLAGS: ${HDF5++_LDFLAGS}")
	message(STATUS "HDF5++_CPPFLAGS: ${HDF5++_CPPFLAGS}")
endif (NOT HDF5++_FIND_QUIETLY)
